### ISSUE TITLE
Repositry Excluded

### ISSUE THREAD

**Issue by pravocodes** [Shubhanshu-1507/Sourcecode#331]
your repo is excluded form Hacktoberfest can you look into it once.

**Comment by pravocodes** [comment]
![image](https://github.com/user-attachments/assets/cdcb1c6c-66b0-42e2-afca-603140c22df1)

**Comment by Shubhanshu-1507** [comment]
> ![image](https://github.com/user-attachments/assets/cdcb1c6c-66b0-42e2-afca-603140c22df1)
> 

Yes , it got excluded , I already post a announcement update in readme , read it for full info, ( someone might have reported or maybe I have merged a lot PR, maybe they don't align with their value & that's why they excluded, nothing is clear but it got excluded & any contribution won't count that's why I haven't accepted new PR merged request) , so now I will accept only valid PR in new repo ( I will make one )
